### ISSUE TITLE
won't run 2.6.9  in travis

### ISSUE THREAD

**Issue by realopenit** [realopenit/bubble#9]
https://travis-ci.org/realopenit/bubble/jobs/152694191

Exception ImportError: No module named ordereddict

Traceback (most recent call last):

  File "/home/travis/virtualenv/python2.6.9/bin/behave", line 11, in <module>

```
sys.exit(main())
```

  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/behave/**main**.py", line 109, in main

```
failed = runner.run()
```

  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/behave/runner.py", line 672, in run

```
return self.run_with_paths()
```

  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/behave/runner.py", line 678, in run_with_paths

```
self.load_step_definitions()
```

  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/behave/runner.py", line 658, in load_step_definitions

```
exec_file(os.path.join(path, name), step_module_globals)
```

  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/behave/runner.py", line 304, in exec_file

```
exec(code, globals, locals)
```

  File "features/steps/transform_steps.py", line 9, in <module>

```
from bubble.transformer import Transformer
```

  File "/home/travis/build/realopenit/bubble/bubble/**init**.py", line 12, in <module>

```
from ordereddict import OrderedDict
```

ImportError: No module named ordereddict

**Comment by realopenit** [comment]
fixed  https://travis-ci.org/realopenit/bubble/jobs/152888126

for we will "pip install " the missing 2.6.9 requirements,
but should that fail, you can "easy_install" them afterwards.
like:

# wget https://bootstrap.pypa.io/ez_setup.py -O - | python

# easy_install importlib

# easy_install ordereddict
